version: '2'
services:
    # ltc is an image of litecoin node which used as base image for ltcd and
    # ltcctl. The environment variables default values determined on stage of
    # container start within starting script.
    ltcd:
      image: ltcd
      container_name: ltcd
      build:
        context: ltcd/
      volumes:
        - shared:/rpc
        - litecoin:/data
      environment:
        - RPCUSER
        - RPCPASS
        - NETWORK
        - DEBUG
        - MINING_ADDRESS
      entrypoint: ["./start-ltcd.sh"]

    broln:
      image: broln
      container_name: broln_ltc
      build:
        context: ../
        dockerfile: dev.Dockerfile
      environment:
        - RPCUSER
        - RPCPASS
        - NETWORK
        - CHAIN=litecoin
        - DEBUG
      volumes:
        - shared:/rpc
        - broln_ltc:/root/.broln
      entrypoint: ["./start-broln.sh"]
      links:
        - "ltcd:blockchain"

volumes:
  # shared volume is need to store the brond rpc certificates and use it within
  # ltcctl and broln containers.
  shared:
    driver: local

  # litecoin volume is needed for maintaining blockchain persistence
  # during ltcd container recreation.
  litecoin:
    driver: local

  # broln volume is used for persisting broln application data and chain state
  # during container lifecycle.
  broln_ltc:
    driver: local
